# Generated by Django 3.2.24 on 2024-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('subcategory', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('published_date', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('ave_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('cover', models.CharField(blank=True, choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover')], max_length=20, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=25, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=254, null=True)),
                ('cover_artist', models.CharField(blank=True, max_length=254, null=True)),
            ],
            bases=('products.product',),
        ),
    ]
