# Generated by Django 3.2.24 on 2024-02-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240225_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
