# Generated by Django 3.2.24 on 2024-03-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ave_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='Non Available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
