# Generated by Django 3.2.24 on 2024-03-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240301_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ave_rating',
            new_name='rating',
        ),
    ]
